baseURL: http://localhost:1313/
relativeURLs: true # 开发环境下需要设置为true，否则iframe会加载失败
languageCode: en-us
title: Alex' Data Analytics Blog
# module:
#   imports:
#   - path: github.com/imfing/hextra
theme: hextra
ignoreFiles:
- ".Rmd$"
- ".ipynb$"
- ".py$"
- ".qmd$"
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block: [['\[', '\]'], ['$$', '$$']]
          inline: [['\(', '\)']]
        enable: true

enableInlineShortcodes: true


menu:
  main:
    - identifier: documentation
      name: Documentation
      pageRef: /docs
      weight: 1
    - identifier: dashboard
      name: Dashboard
      pageRef: /dashboard
      weight: 1.5
    - identifier: blog
      name: Blog
      pageRef: /blog
      weight: 2
    - identifier: tags
      name: Tags
      pageRef: /tags
      weight: 3
    - identifier: about
      name: About
      pageRef: /about
      weight: 4
    - name: Search
      weight: 5
      params:
        type: search
    - name: GitHub
      weight: 6
      url: "https://github.com/alexwoo79/qhs"
      params:
        icon: github
  sidebar:
    - identifier: more
      name: More
      params:
        type: separator
      weight: 1
    - identifier: about
      name: "About"
      pageRef: "/about"
      weight: 2
    - identifier: hugoDocs
      name: "Hugo Docs ↗"
      url: "https://gohugo.io/documentation/"
      weight: 3
    
params:
# Display the last modification date
  displayUpdatedDate: true
  dateFormat: "January 2, 2006"
  # Search
  # flexsearch is enabled by default
  search:
    enable: true
    type: flexsearch

    flexsearch:
      # index page by: content | summary | heading | title
      index: content
      # full | forward | reverse | strict
      # https://github.com/nextapps-de/flexsearch/#tokenizer-prefix-search
      tokenize: forward

  editURL:
    enable: true
    base: "https://github.com/alexwoo79/qhs/edit/main/docs/content"

  blog:
    list:
      displayTags: true
      # date | lastmod | publishDate | title | weight
      sortBy: date
      sortOrder: desc # or "asc"
      # Pagination
      pagerSize: 20

    article:
      displayPagination: true

  toc:
    displayTags: true

  highlight:
    copy:
      enable: true
      # hover | always
      display: hover

  page:
    # full (100%), wide (90rem), normal (80rem)
    width: normal
    # tabs:
    #   sync: true

  # comments:
  #   enable: false
  #   type: giscus

    # https://giscus.app/
    # giscus:
    #   repo: imfing/hextra
    #   repoId: R_kgDOJ9fJag
    #   category: General
    #   categoryId: DIC_kwDOJ9fJas4CY7gW
      # mapping: pathname
      # strict: 0
      # reactionsEnabled: 1
      # emitMetadata: 0
      # inputPosition: top
      # lang: en
      # theme: noborder_dark